### Find all users
GET http://localhost:3333/user?displayName=Leon&maxResults=12&pageNumber=0
Content-Type: application/json
Authorization: Bearer {{token}}

### Find user by id
GET http://localhost:3333/user/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Create user
POST http://localhost:3333/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "{{$random.alphanumeric(12)}}",
  "email": "{{$random.email}}",
  "phone": "(64) 93814-4245",
  "lastName": "Dias Santos",
  "firstName": "Leonardo",
  "displayName": "Leon"
}

### Update user by id
PATCH http://localhost:3333/user/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "{{$random.email}}",
  "phone": "(97) 92263-1613",
  "lastName": "Gomes Silva",
  "firstName": "Eduardo",
  "displayName": "Edu"
}

### Find current user profile
GET http://localhost:3333/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

### Update current user profile
PATCH http://localhost:3333/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "{{$random.email}}",
  "phone": "(97) 92263-1613",
  "lastName": "Gomes Silva",
  "firstName": "Eduardo",
  "displayName": "Edu"
}
